#!/bin/sh -e
# initramfs hook for casper

PREREQS=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQS"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules unionfs
manual_add_modules aufs
manual_add_modules overlayfs

# unionfs-fuse, if available
if [ -x /usr/bin/unionfs-fuse ]; then
    copy_exec /usr/bin/unionfs-fuse /bin
fi

# We need losetup
copy_exec /sbin/losetup /sbin

mkdir -p ${DESTDIR}/lib/udev/rules.d
cp -p /lib/udev/rules.d/60-cdrom_id.rules ${DESTDIR}/lib/udev/rules.d/
copy_exec /lib/udev/cdrom_id /lib/udev

# squashfs
manual_add_modules squashfs
manual_add_modules loop

# random file system modules
manual_add_modules ext4

# cdrom modules
manual_add_modules sr_mod

cp /usr/share/initramfs-tools/scripts/casper-functions $DESTDIR/scripts
cp /usr/share/initramfs-tools/scripts/casper-helpers $DESTDIR/scripts

auto_add_modules net

if [ -e /etc/casper.conf ]; then
    mkdir -p ${DESTDIR}/etc
    cp /etc/casper.conf ${DESTDIR}/etc
fi
